// ui-scenes.mjs — generates src/ui/scenes.ts from the kit's screen templates (ui/scenes/*.svg +
// .tml.svg + .contract.xml), so a game can use them without copying: popups: { settings: UI_SCENES.settings }.
// Run by `npm run build` (and checked by test/ui.test.ts). `components` and `effects` are showcases, not templates.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'ui/scenes');
const SKIP = new Set(['components', 'effects']);

export function generate() {
  const names = readdirSync(dir)
    .filter((f) => f.endsWith('.svg') && !f.endsWith('.tml.svg'))
    .map((f) => f.slice(0, -4))
    .filter((n) => !SKIP.has(n))
    .sort();
  const read = (f) => JSON.stringify(readFileSync(join(dir, f), 'utf8'));
  const body = names
    .map((n) => `  ${n}: {\n    base: ${read(`${n}.svg`)},\n    heir: ${read(`${n}.tml.svg`)},\n    contract: ${read(`${n}.contract.xml`)},\n  },`)
    .join('\n');
  return `// scenes.ts — GENERATED by scripts/ui-scenes.mjs from ui/scenes/ (do not edit): the kit's screen
// templates built from its UI components (design 720×1280). Use as a screen / popup / overlay:
//   popups: { settings: UI_SCENES.settings, pause: UI_SCENES.pause }
// or copy the files from @trempel/kit/ui/scenes/ to change the layout.

import type { SceneSource } from './screen.js';

export const UI_SCENES = {
${body}
} satisfies Record<string, Required<SceneSource>>;

export type UISceneName = keyof typeof UI_SCENES;
`;
}

const out = join(root, 'src/ui/scenes.ts');
if (process.argv[2] === '--check') {
  if (readFileSync(out, 'utf8') !== generate()) {
    console.error('src/ui/scenes.ts is stale — run node scripts/ui-scenes.mjs');
    process.exit(1);
  }
} else if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(out, generate());
  console.log(`ui-scenes → ${out}`);
}
