// format.ts — the skin as data (skin.json: tokens, the role map, measured files).
//
// A skin is a FOLDER:
//   skin.json      tokens (hand-written): colours, fonts, radii, procedural states (pressed /
//                  disabled / hover), the slot-icon mode, 9-slice scale, `stretch` (which art is
//                  9-slice) + `files` (generated by `trempel-skin`: pixel size and 9-slice borders
//                  measured on the art — never typed in);
//   skin-map.json  role → art: a file of the folder, `null` (the role is drawn by another role's
//                  art — hidden), `{ "fill": "<colour token>" }` (procedural fill) or
//                  `{ "keep": "<why>" }` (no pair in this skin — the scene's own art stays);
//   *.png          the sprites (bundled as they are or as copies the CLI writes).
// Kit components draw ROLES (button.primary, panel, slot.plate…, see ROLES below); a role the map
// does not name is drawn procedurally from the tokens — the default skin names none.
// Pure (no Pixi): validated by validateSkin(), unit-tested.

export type Slice = [number, number, number, number];

export interface SkinFile {
  /** Pixel size of the art. */
  size: [number, number];
  /** 9-slice borders L T R B, art px (stretchable art only). */
  slice?: Slice;
}

export interface SkinFont {
  family: string;
  /** Font file (bundled by the game: assets.fonts). */
  file?: string;
  weight?: string;
  license?: string;
}

export type SlotIconMode = 'color' | 'grayscale' | 'silhouette';
export const SLOT_ICON_MODES: readonly SlotIconMode[] = ['color', 'grayscale', 'silhouette'];

export interface SkinStates {
  /** Held button: scale (ButtonFX) and a darkening multiplier of the colour. */
  pressed: { scale: number; darken: number };
  /** Disabled: saturation (0 = grey) and brightness multipliers, alpha. */
  disabled: { saturation: number; darken: number; alpha?: number };
  /** Mouse over: brightness multiplier (1 = none). */
  hover?: { brighten: number };
}

export interface SkinJson {
  name?: string;
  /** Colour tokens: '#rrggbb'. */
  colors: Record<string, string>;
  /** heading — titles, numbers, buttons; text — everything else. */
  fonts: { heading: SkinFont; text: SkinFont };
  /** Corner radii by component, design units ('pill' = half the height). */
  radii?: Record<string, number | 'pill'>;
  /** Outline width of procedural plates (design units, 0 = none). */
  outline?: number;
  states: SkinStates;
  /** How a slot icon looks before it is found. */
  slotIcon?: SlotIconMode;
  /** Design units per art px of 9-slice art: 'height' = box height / art height; a number = fixed. */
  slice?: Record<string, number | 'height'> & { default?: number | 'height' };
  /** Art files that are 9-slice (the CLI measures their borders). */
  stretch?: string[];
  /** Generated by `trempel-skin`. */
  files?: Record<string, SkinFile>;
}

export type RoleValue = string | null | { fill: string } | { keep: string };

export interface SkinMap {
  roles: Record<string, RoleValue>;
  /** Art used directly by scenes (not a role): name → file. Documentation + the bundle list. */
  added?: Record<string, string>;
}

/**
 * Roles the kit's components draw. `<variant>` — any name; the procedural look takes its colour
 * from the token of the same name (`button.primary` → colors.primary, label → colors.onPrimary).
 */
export const ROLES = {
  'button.<variant>': 'wide button plate (9-slice); variants primary | secondary | danger | neutral | any token',
  iconButton: 'round button plate',
  'icon.<name>': 'icon glyph (close, pause, play, settings, back, home, restart, sound-on, sound-off, music-on, music-off, hint, video, plus, check, lock, star)',
  plate: 'title plate / pill (9-slice)',
  panel: 'light panel (9-slice)',
  'panel.dark': 'dark panel (9-slice)',
  popup: 'popup frame (9-slice)',
  'popup.title': 'title plate of the popup frame (default: plate)',
  'slot.plate': 'round icon slot plate',
  'slot.found': 'found mark of a slot',
  'slot.hint': 'hint glow ring of a slot',
  badge: 'counter badge',
  'progress.track': 'progress bar track (9-slice)',
  'progress.fill': 'progress bar fill (9-slice)',
  'slider.track': 'segmented slider: empty segment (fill token)',
  'slider.fill': 'segmented slider: filled segment (fill token)',
  'slider.knob': 'segmented slider knob',
  'star.full': 'result star, earned',
  'star.empty': 'result star, not earned',
} as const;

const HEX = /^#[0-9a-fA-F]{6}$/;

/** Every problem of a skin (empty = valid). `exists(file)` checks the art files when given. */
export function validateSkin(json: SkinJson, map: SkinMap = { roles: {} }, exists?: (file: string) => boolean): string[] {
  const errors: string[] = [];
  if (!json || typeof json !== 'object') return ['skin.json: not an object'];
  for (const [k, v] of Object.entries(json.colors ?? {})) if (!HEX.test(v)) errors.push(`colors.${k}: "${v}" is not #rrggbb`);
  if (!json.colors) errors.push('colors: missing');
  for (const r of ['heading', 'text'] as const) if (!json.fonts?.[r]?.family) errors.push(`fonts.${r}.family: missing`);
  const st = json.states;
  if (!st?.pressed || typeof st.pressed.scale !== 'number' || typeof st.pressed.darken !== 'number') errors.push('states.pressed: { scale, darken } numbers');
  if (!st?.disabled || typeof st.disabled.saturation !== 'number' || typeof st.disabled.darken !== 'number') errors.push('states.disabled: { saturation, darken } numbers');
  if (json.slotIcon && !SLOT_ICON_MODES.includes(json.slotIcon)) errors.push(`slotIcon: "${json.slotIcon}" (known: ${SLOT_ICON_MODES.join(', ')})`);
  for (const [k, v] of Object.entries(json.radii ?? {})) if (v !== 'pill' && !(typeof v === 'number' && v >= 0)) errors.push(`radii.${k}: number ≥ 0 or "pill"`);
  for (const [k, v] of Object.entries(json.slice ?? {})) if (!k.startsWith('$') && v !== 'height' && !(typeof v === 'number' && v > 0)) errors.push(`slice.${k}: "height" or a number > 0`);
  const files = json.files ?? {};
  for (const s of json.stretch ?? []) if (json.files && !files[s]?.slice) errors.push(`stretch: ${s} has no measured 9-slice in files (run trempel-skin)`);
  for (const [f, m] of Object.entries(files)) {
    if (!Array.isArray(m.size) || m.size.length !== 2) errors.push(`files.${f}: size [w, h]`);
    if (m.slice) {
      const [l, t, r, b] = m.slice;
      if (l + r >= m.size[0] || t + b >= m.size[1]) errors.push(`files.${f}: 9-slice borders ${m.slice.join(' ')} do not fit ${m.size.join('×')}`);
    }
  }
  const art = (role: string, file: string) => {
    if (json.files && !files[file]) errors.push(`${role} → ${file}: not in skin.json files (run trempel-skin)`);
    if (exists && !exists(file)) errors.push(`${role} → ${file}: file missing`);
  };
  for (const [role, v] of Object.entries(map.roles ?? {})) {
    if (role.startsWith('$')) continue;
    if (typeof v === 'string') art(`roles.${role}`, v);
    else if (v === null) continue;
    else if (v && typeof v === 'object' && 'fill' in v) {
      if (!json.colors?.[v.fill]) errors.push(`roles.${role}: fill token "${v.fill}" is not a colour`);
    } else if (v && typeof v === 'object' && 'keep' in v) continue;
    else errors.push(`roles.${role}: a file, null, { fill } or { keep }`);
  }
  for (const [name, f] of Object.entries(map.added ?? {})) if (!name.startsWith('$')) art(`added "${name}"`, f);
  return errors;
}
